name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate profile 3D contrib
        uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Th3Wolfe

      - name: Commit result
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          git add .
      
          git commit -m "generate 3d contrib graph" || echo "No changes to commit"
      
          git push origin main
